# Generated by Django 4.1 on 2022-08-14 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(help_text='Date for which the timestamp is registered', verbose_name='Date')),
                ('time', models.PositiveIntegerField(help_text='Number of registered hours', verbose_name='Time')),
                ('project', models.ForeignKey(help_text='Project for which the timestamp is registered', on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='projects.project', verbose_name='Project')),
                ('user', models.ForeignKey(help_text='User whose time was registered', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
