# Generated by Django 4.1 on 2022-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
