# Generated by Django 4.1 on 2022-08-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_name'),
        ('users', '0003_remove_user_projects_delete_userprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='users', to='projects.project'),
        ),
    ]
